spring:
  application:
    name:
      cloud-file-storage

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  config:
    import: file:.env[.properties]

  liquibase:
    enabled: true

  minio:
    endpoint: http://localhost:9000
    username: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    bucket-name: user-files

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}

  data:
    redis:
      password: ${REDIS_PASSWORD}

server:
  tomcat:
    max-part-count: 100